//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clawSoft.clawPDF.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clawSoft.clawPDF.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eciRGB_v2 {
            get {
                object obj = ResourceManager.GetObject("eciRGB_v2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ISOcoated_v2_300_eci {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_300_eci", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ISOcoated_v2_grey1c_bas {
            get {
                object obj = ResourceManager.GetObject("ISOcoated_v2_grey1c_bas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!
        ///% This is a sample prefix file for creating a PDF/A document.
        ///% Users should modify entries marked with &quot;Customize&quot;.
        ///% This assumes an ICC profile resides in the file (srgb.icc),
        ///% in the current directory unless the user modifies the corresponding line below.
        ///
        ///% Define entries in the document Info dictionary :
        ///[ /Title (Title)       % Customise
        ///  /DOCINFO pdfmark
        ///
        ///% Define an ICC profile :
        ////ICCProfile [ICC_PROFILE]
        ///def
        ///
        ///[/_objdef {icc_PDFA} /type /stream /OBJ pdfmark
        ///
        ///%% This code attemp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PdfaDefinition {
            get {
                return ResourceManager.GetString("PdfaDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!
        ///% This is a sample prefix file for creating a PDF/X-3 document.
        ///% Users should modify entries marked with &quot;Customize&quot;.
        ///% This assumes an ICC profile resides in the file (ISO Coated sb.icc)
        ///% in the current directory unless the user modifies the corresponding line below.
        ///
        ///% First up, attempt to ensure the user has set ColorConversionStrategy correctly.
        ///% PDF/X-3 only permits Gray or CMYK in the output.
        ///%
        ///systemdict /ColorConversionStrategy known {
        ///  systemdict /ColorConversionStrategy get cvn du [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PdfxDefinition {
            get {
                return ResourceManager.GetString("PdfxDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %!PS
        ////stampstring ([STAMPSTRING]) def
        ////fontname /[FONTNAME] def
        ////fontsize [FONTSIZE] def
        ////fontcolor {[FONTCOLOR]} def
        ////ISOLatin1Encoding [
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef/.notdef
        ///    /space/exclam/quotedbl/numbersign/dollar/percent/ampersand/quoteright
        ///    /parenle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostScriptStamp {
            get {
                return ResourceManager.GetString("PostScriptStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WebCoatedFOGRA28 {
            get {
                object obj = ResourceManager.GetObject("WebCoatedFOGRA28", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
